import { type AgeRange } from './AgeRange';
import { type Channel } from './Channel';
import { type Collection } from './Collection';
import { type Escort } from './Escort';
import { type Genre } from './Genre';
import { type Language } from './Language';
import { type Live } from './Live';
import { type MConfigsRtvePlayEstructura } from './MConfigsRtvePlayEstructura';
import { type PlayIndexApps } from './PlayIndexApps';
import { type Previews } from './Previews';
import { type Program } from './Program';
import { type ProgramType } from './ProgramType';
import { type PubState } from './PubState';
import { type RecommendAgesForChild } from './RecommendAgesForChild';
import { type RrssApp } from './RrssApp';
import { type SearchResults } from './Search';
import { type Season } from './Season';
import { type Token } from './Token';
import { type Video } from './Video';

export interface RTVE {
  AgeRange: AgeRange;
  Channel: Channel;
  Collection: Collection;
  Escort: Escort;
  Genre: Genre;
  Language: Language;
  Live: Live;
  MConfigsRtvePlayEstructura: MConfigsRtvePlayEstructura;
  PlayIndexApps: PlayIndexApps;
  Previews: Previews;
  Program: Program;
  ProgramType: ProgramType;
  PubState: PubState;
  RecommendAgesForChild: RecommendAgesForChild;
  RrssApp: RrssApp;
  Season: Season;
  SearchResults: SearchResults;
  Token: Token;
  Video: Video;
}
