import RTVE from '.';

export default interface Video {
  uri: string;
  htmlUrl: string;
  htmlShortUrl: string;
  id: string;
  language: RTVE['Language'];
  anteTitle: null | string;
  anteTitleUrl: null;
  longTitle: string;
  shortTitle: null | string;
  mainCategoryRef: string;
  popularity: string;
  popHistoric: string;
  numVisits: string;
  publicationDate: string;
  modificationDate: string;
  pubState: RTVE['PubState'];
  mainTopic: string;
  topicsName: string[];
  breadCrumbRef: string;
  imageSEO: string;
  thumbnail: null | string;
  previews: RTVE['Previews'];
  expirationDate: null | string;
  dateOfEmission: string;
  publicationDateTimestamp: number;
  productionDate: null;
  contentType: 'video';
  consumption: string;
  type: {
    id: number;
    name: string;
  };
  subType: {
    id: number;
    name: string;
  } | null;
  assetType: 'video';
  statistics: {
    numComentarios: number;
    numCompartidas: number;
  };
  alt: null | string;
  foot: null;
  shortDescription: null | string;
  description: null | string;
  otherTopicsRefs: string;
  qualities: {
    identifier: number;
    filePath: string;
    preset: 'HD_FULL' | 'HD_READY' | 'HQ' | 'HIGH' | 'MED';
    filesize: number | null;
    type: string;
    duration: number;
    bitRate: number;
    bitRateUnit: string;
    language: RTVE['Language'];
    previewPath: string;
    height: number;
    width: number;
  }[];
  qualitiesRef: string;
  duration: number;
  programInfo: {
    id: string;
    title: string;
    htmlUrl: string;
    channelPermalink: string;
    ageRangeUid: RTVE['AgeRange']['AgeRangeUid'] | null;
    ageRange: RTVE['AgeRange']['AgeRange'] | null;
    programType: string;
    programTypeId: string;
    outOfEmission: boolean;
  };
  sgce: null | string;
  dg: null | string;
  sip: null;
  commentOptions: null;
  cuePointsRef: string;
  configPlayerRef: string;
  transcriptionRef: string;
  temporadaId: number | null;
  temporadasRef: string;
  temporada: null | string;
  temporadaShortTitle: null | string;
  temporadaOrden: number | null;
  programRef: string;
  relacionadosRef: string;
  relManualesRef: string;
  publicidadRef: null;
  comentariosRef: string;
  relatedByLangRef: string;
  sign: {
    ctvId: null;
    name: null;
    firma: null;
    photo: null;
    twitter: null;
    facebook: null;
    otras: null;
    publicationDate: null;
    numPublications: null;
    instagram: null;
  };
  estadisticasRef: string;
  ageRangeUid: RTVE['AgeRange']['AgeRangeUid'] | null;
  ageRange: RTVE['AgeRange']['AgeRange'] | string;
  contentInitDate: null;
  contentEndDate: null;
  disabledAlacarta: boolean;
  notDownloadable: boolean;
  noRegistrationRequired: boolean;
  promoTitle: null;
  promoDesc: null;
  episode: number;
  subtitleRef: null | string;
  aspectRatio: 'f16x9';
  title: string;
  idWiki: null;
  idImdb: null;
  director: null | string;
  producedBy: null;
  showMan: null | string;
  casting: null | string;
  generos: RTVE['Genre'][];
  technicalTeam: null;
  audioDescription: null | string;
  audioOriginal: null | string;
  allowedInCountry: boolean;
  paidContent: boolean;
  geolocalizado: boolean;
  paidCountries: null;
  escort: RTVE['Escort'] | null;
  hasCuePoints: boolean;
  country: 'ES';
  hasDRM: boolean;
  requireLogged: boolean;
  consumptionUid?: string;
}
