import RTVE from '.';

export default interface AgrProgramas {
  uri: string;
  htmlUrl: string;
  htmlShortUrl: string;
  id: string;
  ctvId: number | null;
  oldCtvId: null;
  uid: string;
  name: string;
  permalink: string;
  language: string;
  longTitle: string;
  shortTitle: string;
  description: null | string;
  audioDescription: boolean;
  longDescription: string;
  contact: null;
  emission: null | string;
  publicationDate: string;
  expirationDate: null;
  pubState: RTVE['PubState'];
  orden: number;
  imageSEO: string;
  logo: null | string;
  logo2: string;
  thumbnail: string;
  imgBackground: string;
  imgBackground2: string;
  imgPoster: string;
  imgPoster2: string;
  imgPortada: string;
  imgPortada2: string;
  imgCol: string;
  imgCol2: string;
  imgCol3: string;
  imgBanner: string;
  imgBanner2: string;
  imgPinta: string;
  imagePodcast: string;
  outOfEmission: boolean;
  channel: RTVE['Channel'];
  fanBoxID: null;
  ageRangeUid: RTVE['AgeRange']['AgeRangeUid'] | null;
  ageRange: RTVE['AgeRange']['AgeRange'] | null;
  recommendAgesForChilds: RTVE['RecommendAgesForChild'][];
  seccionesRef: string;
  temporadasRef: string;
  temporadaShortTitle: null;
  temporada: null;
  agrupadoresRef: string;
  videosRef: string;
  audiosRef: string;
  multimediasRef: string;
  relacionadosRef: string;
  otherChannelsRef: string;
  childrenInfoRef: string;
  filtro: null;
  webRtve: null | string;
  webOficial: string;
  promoText: null | string;
  promoDesc: null | string;
  relatedByLangRef: string;
  modificationDate: string;
  publicationDateTimestamp: number;
  contentType: 'programa';
  sgce: null | string;
  sgce2: null | string;
  kantar: null | string;
  generos: RTVE['Genre'][] | null;
  seasons: RTVE['Season'][] | null;
  numSeasons: number;
  productionDate: null | string;
  rrss: null | string;
  rrssApps: RTVE['RrssApp'][];
  mainTopic: string;
  mainTopicUid: string;
  title: string;
  disabledAlacarta: boolean;
  programType: string | null;
  programTypeId: number | null;
  isComplete: boolean;
  inAZList: boolean;
  director: null | string;
  producedBy: null | string;
  showMan: null | string;
  casting: null | string;
  technicalTeam: null | string;
  idWiki: null | string;
  idImdb: string;
  showFragments: boolean;
  notDownloadable: boolean;
  paidCountries: null;
  escort: RTVE['Escort'];
}
