export default interface Genero {
  generoInf: GeneroInf;
  generoInfUid: GeneroInfUid;
  generoId: string;
  subGeneroInf?: SubGeneroInf;
  subGeneroInfUid?: SubGeneroInfUid;
  subGeneroId?: string;
}

type GeneroInf =
  | 'Humor'
  | 'Cultura'
  | 'Deportes'
  | 'Infantil'
  | 'Playz joven'
  | 'Ciencia y futuro'
  | 'Información y actualidad'
  | 'Historia'
  | 'Viajes'
  | 'Archivo TVE'
  | 'Drama'
  | 'Comedia'
  | 'Servicio Público'
  | 'Biografías'
  | 'Música'
  | 'Romántica'
  | 'Policíaca y suspense'
  | 'Moda, famosos y tendencias'
  | 'Series Históricas'
  | 'Series'
  | 'Cocina'
  | 'Terror'
  | 'Series Literarias'
  | 'Cataluña'
  | 'Igualdad'
  | 'Acción y aventuras'
  | 'TV Movies'
  | 'Sobremesa'
  | 'Series en Catalán';

type GeneroInfUid =
  | 'GEN_HUMOR'
  | 'GEN_CULTU'
  | 'GE_DEPOR'
  | 'GE_INFAN'
  | 'GE_PLAYZ'
  | 'GE_CIENFU'
  | 'GE_INFOR'
  | 'GEN_HISTO'
  | 'GEN_VIAJE'
  | 'GE_ARTVECC'
  | 'GE_DRAMA'
  | 'GE_COMED'
  | 'GEN_SERPU'
  | 'GEN_BIOGR'
  | 'GEN_MUSIC'
  | 'GEN_ROMAN'
  | 'GE_POYDSUS'
  | 'GE_MOFAT'
  | 'GE_SERHIS'
  | 'GE_SERIES'
  | 'GEN_COCIN'
  | 'GE_TERROR'
  | 'GE_SERLIT'
  | 'GEN_CATAL'
  | 'GEN_IGUAL'
  | 'GE_ACYAVET'
  | 'GE_TVMOVI'
  | 'GE_SOMESA'
  | 'GE_SERCAT';

type SubGeneroInf =
  | 'Olimpismo'
  | 'Ciclismo'
  | 'Naturaleza y Medio ambiente'
  | 'Fútbol'
  | 'Educación'
  | 'Rock/Pop'
  | 'Cine'
  | 'Literatura'
  | 'Arte'
  | 'Tecnología'
  | 'Documentales'
  | 'Arquitectura'
  | 'Músicas del mundo'
  | 'Clásica'
  | 'Hip hop/Funk'
  | 'Religiosos'
  | 'Vela'
  | 'Electrónica/Experimental'
  | 'Eurovisión'
  | 'Atletismo'
  | 'Deportes de invierno'
  | 'Baloncesto'
  | 'Jazz/Blues'
  | 'Hípica'
  | 'Masterchef'
  | 'Motor'
  | 'OT'
  | 'Danza'
  | 'Gimnasia'
  | 'Fotografía'
  | 'Artes marciales'
  | 'Natación'
  | 'Balonmano'
  | 'Tenis'
  | 'Voleibol'
  | 'Rugby'
  | 'Bádminton';

type SubGeneroInfUid =
  | 'GEN_OLIPM'
  | 'GEN_CICLI'
  | 'GEN_MEDAM'
  | 'GEN_FUTBOL'
  | 'GEN_EDUCA'
  | 'GEN_ROCKP'
  | 'GEN_CINEC'
  | 'GEN_LITER'
  | 'GEN_ARTEC'
  | 'GEN_TECNO'
  | 'GEN_DOCUM'
  | 'GEN_ARQUI'
  | 'GEN_MUMUD'
  | 'GEN_CLASIC'
  | 'GEN_HIPHOP'
  | 'GEN_RELIG'
  | 'GEN_VELAC'
  | 'GEN_ELEEX'
  | 'GEN_EUROV'
  | 'GEN_ATLET'
  | 'GEN_INVIER'
  | 'GEN_BALON'
  | 'GEN_JAZZB'
  | 'GEN_HIPIC'
  | 'GEN_MCHEF'
  | 'GEN_MOTOR'
  | 'GEN_OTMUS'
  | 'GEN_DANZA'
  | 'GEN_GIMNA'
  | 'GEN_FOTOG'
  | 'GEN_ARTMC'
  | 'GEN_NATAC'
  | 'GEN_BALOM'
  | 'GEN_TENIS'
  | 'GEN_VOLEI'
  | 'GEN_RUGBY'
  | 'GEN_BADMI';
