type ProgramType =
  | 'Series de Archivo'
  | 'Magacines'
  | 'Infantiles'
  | 'Entrevistas'
  | 'Magacín semanal'
  | 'Serie Documental'
  | 'Especial Evento'
  | 'Concursos'
  | 'Informativos Noticias'
  | 'Entretenimiento'
  | 'Series'
  | 'Documental Original'
  | 'Series Internacionales'
  | 'Informativo diario'
  | 'Series Prime Time'
  | 'Talent'
  | 'Reportajes Factual'
  | 'Documental'
  | 'Conciertos'
  | 'Series Ficción Originales'
  | 'Magacines diarios'
  | 'Late Night'
  | 'Series Diarias'
  | 'Recetas'
  | 'Series catalán'
  | 'Contenedor Películas';

export default ProgramType;
